Abeeway
akenza-io/device-type-library pull request #134
Opened 2022-02-22 17:00 UTC by J2thatsme

Will add more topics later, tests work.

2022-02-28 07:38 UTC, mariusgiger requested changes
nice work! I think we need to review the topic structure again, please prepare a page/diagram listing which message ends up in which topic.

2022-02-28 07:38 UTC, mariusgiger commented on types/abeeway/badgeTracker/acknowledge.schema.json
> +  "$id": "https://akenza.io/abeeway/compactTracker/acknowledge.schema.json",
why does this need a separate schema?

2022-02-28 07:38 UTC, mariusgiger commented on types/abeeway/badgeTracker/activity_status.schema.json
> +  "$id": "https://akenza.io/abeeway/compactTracker/activity_status.schema.json",
why does this need a separate schema?

2022-02-28 07:38 UTC, mariusgiger commented on types/abeeway/badgeTracker/ble_beacon_failure.schema.json
> +  "$id": "https://akenza.io/abeeway/compactTracker/ble_beacon_failure.schema.json",
why does this need a separate schema?

2022-02-28 07:38 UTC, mariusgiger commented on types/abeeway/badgeTracker/ble_beacon_long.schema.json
> +  "$id": "https://akenza.io/abeeway/compactTracker/ble_beacon_long.schema.json",
why does this need a separate schema? just add all these values to lifecycle

2022-02-28 07:38 UTC, mariusgiger commented on types/abeeway/badgeTracker/ble_connected.schema.json
> +  "$id": "https://akenza.io/abeeway/compactTracker/ble_connected.schema.json",
placeholder?

2022-02-28 07:38 UTC, mariusgiger commented on types/abeeway/badgeTracker/ble_bond_deleted.schema.json
> +  "$id": "https://akenza.io/abeeway/compactTracker/ble_bond_deleted.schema.json",
placeholder?

2022-02-28 07:38 UTC, mariusgiger commented on types/abeeway/badgeTracker/ble_disconnected.schema.json
> +  "$id": "https://akenza.io/abeeway/compactTracker/ble_disconnected.schema.json",
placeholder?

2022-02-28 07:38 UTC, mariusgiger commented on types/abeeway/badgeTracker/encrypted_wifi_bssid.schema.json
> +  "$id": "https://akenza.io/abeeway/compactTracker/encrypted_wifi_bssid.schema.json",
placeholder?

2022-02-28 07:38 UTC, mariusgiger commented on types/abeeway/badgeTracker/meta.json
> +    "acknowledge",
I think this is definitely too many topics. Can you try to separate the messages into control and data messages and for the control ones you use the lifecycle topic?

2022-02-28 07:38 UTC, mariusgiger commented on types/abeeway/badgeTracker/uplink.js
> +  switch (operatingMode) {
possibly extract this into a separate function

2022-02-28 07:38 UTC, mariusgiger commented on types/abeeway/badgeTracker/uplink.js
> +  const batteryLevel = Bits.bitsToUnsigned(bits.substr(16, 8));
possibly extract this into a separate function

2022-02-28 07:38 UTC, mariusgiger commented on types/abeeway/badgeTracker/uplink.js
> +  switch (type) {
possibly extract this into a separate function

2022-02-28 07:38 UTC, mariusgiger commented on types/abeeway/microTracker/uplink.js
> +function stepSize(lo, hi, nbits, nresv) {
add a comment explaining that when changing this, the other types also need to be changed

2022-02-28 13:55 UTC, J2thatsme commented on types/abeeway/badgeTracker/activity_status.schema.json
> +  "$id": "https://akenza.io/abeeway/compactTracker/activity_status.schema.json",
activityCounter does only get sent here

2022-03-01 12:50 UTC, J2thatsme commented on types/abeeway/badgeTracker/gps_fix_extended.schema.json
> +  "$id": "https://akenza.io/abeeway/compactTracker/gps_fix_extended.schema.json",
@mariusgiger i cut a lot of the schemas. As indication which message is sent, i defined an enum. Please take a look, and tell me if it makes sense for you.

2022-03-03 07:53 UTC, mariusgiger approved these changes
Nice rework, let's see how it performs in real life.

2022-03-03 09:26 UTC, mariusgiger approved these changes

2022-03-03 09:30 UTC, merged