feature/add-imbuildings-sensors
akenza-io/device-type-library pull request #136
Opened 2022-03-02 15:16 UTC by J2thatsme

Uplinkscript is the same one for all. Office Occupancy & People Counter behave the same way

2022-03-02 17:47 UTC, mariusgiger requested changes
looks good, a few minor comments

2022-03-02 17:47 UTC, mariusgiger commented on .eslintrc.json
> +    "no-plusplus": "off",
why is this turned off? use i += 1; instead

2022-03-02 17:47 UTC, mariusgiger commented on types/IMBuilding/ComfortSensor/meta.json
> +  "manufacturer": "IMBuildings",
change the root directory to match the name of the manufacturer > IMBuildings

2022-03-02 17:47 UTC, mariusgiger commented on types/IMBuilding/OfficeOccupancy/uplink copy.js
> +const payloadTypes = {
remove this unused file

2022-03-02 17:47 UTC, mariusgiger commented on types/IMBuilding/OfficeOccupancy/uplink.js
> +    default:
consider throwing an exception in the default case (unsupported payload)

2022-03-03 09:43 UTC, J2thatsme commented on .eslintrc.json
> +    "no-plusplus": "off",
The explanation on why we should not use ++ is, that the code gets "cryptic". But as i always use it on a single line, it should not lead to errors or complicated code. Excerpt from [stack overflow](https://stackoverflow.com/questions/3000276/the-unexpected-error-in-jslint). Also the IDE generates loops with ++ so should we still go with += 1 ?

2022-03-04 13:34 UTC, mariusgiger commented on .eslintrc.json
> +    "no-plusplus": "off",
refer to https://eslint.org/docs/rules/no-plusplus, it makes sense to not use the operator

2022-03-04 13:34 UTC, mariusgiger commented on types/IMBuilding/ComfortSensor/meta.json
> +  "manufacturer": "IMBuildings",
the root dir is still not changed

2022-03-04 13:35 UTC, mariusgiger approved these changes

2022-03-04 13:41 UTC, merged