Added required in all schemas
akenza-io/device-type-library pull request #194
Opened 2022-12-14 15:29 UTC by J2thatsme

- Added required for keys in schema files
- Renamed image files to be more standardised
- Renamed voltage to batteryVoltage to standardise keys

2023-01-17 11:12 UTC, mariusgiger commented on types/decentlab/IAM/default.schema.json
> -{
@J2thatsme why is this deleted?

2023-01-17 13:20 UTC, J2thatsme commented on types/decentlab/IAM/default.schema.json
> -{
I forgot tho save the changes there.

2023-01-17 13:26 UTC, mariusgiger approved these changes

2023-02-21 08:43 UTC, mariusgiger approved these changes

2023-02-28 07:12 UTC, sevyakenza requested changes
pls check again:
-  Elsys Devices: TYPE_ANALOG2 should be voltage, not batteryVoltage

 - Check difference versions: batteryLevel / batteryCharge / batteryPercent?
 - Also check different description for batteryLevel/Charge/Percent

2023-02-28 11:06 UTC, sevyakenza approved these changes

2023-02-28 11:06 UTC, merged