Cayenne
akenza-io/device-type-library pull request #200
Opened 2023-01-17 13:42 UTC by J2thatsme

2023-01-26 16:28 UTC, mariusgiger requested changes
please align the schema with other types

2023-01-26 16:28 UTC, mariusgiger commented on types/cayenne/cayenne/accelerometer.schema.json
> +    "xAxisAccelerometer": {
please align the naming with other accelerometers

2023-01-26 16:28 UTC, mariusgiger commented on types/cayenne/cayenne/gyrometer.schema.json
> +    "gyroX": {
align this naming with other gyrometers

2023-01-26 16:28 UTC, mariusgiger commented on types/cayenne/cayenne/meta.json
> +  "outputTopics": ["button_pressed", "default", "lifecycle"],
add missing topics

2023-01-30 16:36 UTC, J2thatsme commented on types/cayenne/cayenne/gyrometer.schema.json
> +    "gyroX": {
I do think thats the standard till now

2023-02-27 13:03 UTC, merged