lsn50v2 splitted topics more
akenza-io/device-type-library pull request #222
Opened 2023-04-26 12:09 UTC by J2thatsme

2023-04-27 11:36 UTC, mariusgiger requested changes
looks good only a minor comment

2023-04-27 11:36 UTC, mariusgiger commented on types/dragino/lsn50v2-d20/uplink.js
> +  data = {};
do not reuse variables, instead locally scope the variable

2023-04-27 11:36 UTC, mariusgiger commented on types/dragino/lsn50v2-d22/uplink.js
> +  data = {};
do not reuse variables, instead locally scope the variable

2023-04-27 11:36 UTC, mariusgiger commented on types/dragino/lsn50v2-d23/uplink.js
> +  data = {};
do not reuse variables, instead locally scope the variable

2023-04-27 11:36 UTC, mariusgiger commented on types/dragino/lsn50v2-s31/uplink.js
> +  data = {};
do not reuse variables, instead locally scope the variable

2023-04-27 11:36 UTC, mariusgiger commented on types/dragino/lsn50v2-s31b/uplink.js
> +  data = {};
do not reuse variables, instead locally scope the variable

2023-05-03 11:23 UTC, sevyakenza approved these changes

2023-07-12 08:49 UTC, mariusgiger approved these changes

2023-07-12 09:24 UTC, merged