New VS121 Version.
akenza-io/device-type-library pull request #279
Opened 2024-04-24 15:41 UTC by J2thatsme

Added new functionalities for the new VS121 Version. Update is backwards compatible.

2024-05-18 12:47 UTC, mariusgiger requested changes
Thanks! I have added a few inputs regarding data structuring

2024-05-18 12:47 UTC, mariusgiger commented on types/milesight/VS121/uplink.js
> +      // We probably do not need that atm
use this as the sample timestamp?

2024-05-18 12:47 UTC, mariusgiger commented on types/milesight/VS121/a_flow.schema.json
> +  "title": "A flow",
what does this mean?

2024-05-18 12:47 UTC, mariusgiger commented on types/milesight/VS121/dwell_time.schema.json
> +    "region": {
possibly add a topic per region to make aggregations easier

2024-05-18 12:47 UTC, mariusgiger commented on types/milesight/VS121/region_counter.schema.json
> +      "minimum": 0,
try to add units if possible

2024-05-18 12:47 UTC, mariusgiger commented on types/milesight/VS121/region_counter.schema.json
> +    "region4count": {
possibly rename key to match region4Count to align with camelCase

2024-05-23 13:25 UTC, closed without merging

2024-05-23 13:25 UTC, J2thatsme commented
Changes are included in the VS133 Branch