talkpool
akenza-io/device-type-library pull request #60
Opened 2021-04-07 15:34 UTC by J2thatsme

added both talkpool sensors

2021-04-08 16:00 UTC, mariusgiger requested changes

2021-04-08 16:00 UTC, mariusgiger commented on types/talkpool/oy1210/uplink.js
> +    emit('sample', { data: { "hex": payload }, topic: "startup" });
any chance to decode this as well?

2021-04-08 16:00 UTC, mariusgiger commented on types/talkpool/oy1210/uplink.js
> +
remove unused line

2021-04-08 16:00 UTC, mariusgiger commented on types/talkpool/oy1210/uplink.js
> +    data.temperature = Math.round((Bits.bitsToUnsigned(bits.substr(0, 8) + bits.substr(16, 4)) / 10 - 80) * 10) / 10;
add a comment about the math you are doing here

2021-04-08 16:00 UTC, mariusgiger commented on types/talkpool/oy1210/meta.json
> +    "lifecycle"
lifecycle seems not to exist

2021-04-08 16:00 UTC, mariusgiger commented on types/talkpool/oy1210/uplink.spec.js
> +        if (value.topic === "default") {
verify that a default output has been produced

2021-04-08 16:00 UTC, mariusgiger commented on types/talkpool/oy1700/default.schema.json
> +      "title": "Particles 1.0",
Particulate Matter?

2021-04-08 16:00 UTC, mariusgiger commented on types/talkpool/oy1700/default.schema.json
> +      "title": "Particles 0.3",
include count in the title?

2021-04-08 16:00 UTC, mariusgiger commented on types/talkpool/oy1700/default.schema.json
> +    "particleCount5_": {
_?

2021-04-08 16:00 UTC, mariusgiger commented on types/talkpool/oy1700/startup.schema.json
> +      "description": "Something went wrong while startup."
Description should rather be, Message indicating startup status

2021-04-08 16:00 UTC, mariusgiger commented on types/talkpool/oy1700/uplink.js
> +  emit('sample', { data: data, topic: topic });
rather move this into the brackets to prevent strange things if port > 2

2021-04-08 16:00 UTC, mariusgiger commented on types/talkpool/oy1700/uplink.js
> +      data.particleCount5_ = Bits.bitsToUnsigned(bits.substr(152, 16));
_?

2021-04-08 16:00 UTC, mariusgiger commented on types/talkpool/oy1700/uplink.spec.js
> +        if (value.topic === "default") {
verify that default has been output

2021-04-09 11:14 UTC, J2thatsme commented on types/talkpool/oy1210/uplink.js
> +    emit('sample', { data: { "hex": payload }, topic: "startup" });
kind of

2021-04-15 14:37 UTC, mariusgiger commented on types/talkpool/oy1210/uplink.js
> +      data.message = "Standart startup";
typo Standard

2021-04-15 14:38 UTC, mariusgiger reviewed
minor typo then it is ok

2021-04-16 14:43 UTC, mariusgiger approved these changes

2021-04-19 09:52 UTC, merged