added tekelek oiltank
akenza-io/device-type-library pull request #66
Opened 2021-04-29 09:41 UTC by J2thatsme

2021-04-29 14:02 UTC, mariusgiger requested changes
the uplink decoder is still a bit confusing, please refactor

2021-04-29 14:02 UTC, mariusgiger commented on types/tekelek/TEK766/uplink.js
> +    topic = "paramRead";
why so many different topics with the same structure?

2021-04-30 14:05 UTC, J2thatsme commented on types/tekelek/TEK766/current.schema.json
> +    "SRSSI1": {
There can be multiple datapoints with this value/key in one payload.

2021-04-30 14:06 UTC, J2thatsme commented on types/tekelek/TEK766/current.schema.json
> +    "SRC1": {
There can be multiple datapoints with this value/key in one payload.

2021-04-30 14:06 UTC, J2thatsme commented on types/tekelek/TEK766/lifecycle.schema.json
> +    "batteryLevel": {
yes this one should be the standart from now

2021-04-30 15:06 UTC, mariusgiger commented on types/tekelek/TEK766/current.schema.json
> +    "SRC1": {
ok but those are not in the schema?

2021-04-30 15:07 UTC, mariusgiger commented on types/tekelek/TEK766/lifecycle.schema.json
> +    "batteryLevel": {
ok, please correct it in the other places where still batteryPercent was used

2021-05-25 17:55 UTC, mariusgiger requested changes
thanks for the PR - looks already much better, some comments remain

2021-05-25 17:55 UTC, mariusgiger commented on types/tekelek/TEK766/alarm_history.schema.json
> +    "limit1": {
rename to limit1Exceeded?

2021-05-25 17:55 UTC, mariusgiger commented on types/tekelek/TEK766/alarm_history.schema.json
> +      "description": "The SRSSI is simply an integer number between 1 (low level) and 10 (expected level) given to the expected strength of the echo reflected to the transducer.",
remove simply

2021-05-25 17:55 UTC, mariusgiger commented on types/tekelek/TEK766/lifecycle.schema.json
> +        "Power on reset",
enum values should conform to Java enums POWER_ON_RESET

2021-05-25 17:55 UTC, mariusgiger commented on types/tekelek/TEK766/alarm_history.schema.json
> +      "description": "The SRSSI is simply an integer number between 1 (low level) and 10 (expected level) given to the expected strength of the echo reflected to the transducer.",
do this everywhere

2021-05-25 17:55 UTC, mariusgiger commented on types/tekelek/TEK766/meta.json
> +    "measurement",
missing schemas

2021-05-25 17:55 UTC, mariusgiger commented on types/tekelek/TEK766/param_read.schema.json
> +  "properties": {}
missing properties

2021-05-25 17:55 UTC, mariusgiger commented on types/tekelek/TEK766/uplink.js
> +function getTemperature(temp) {
add a comment to explain this calculation

2021-05-25 17:55 UTC, mariusgiger commented on types/tekelek/TEK766/uplink.js
> +function getUllage(ull1, ull2) {
add a comment to explain this calculation

2021-05-25 17:55 UTC, mariusgiger commented on types/tekelek/TEK766/uplink.js
> +      data = {};
don't reuse variables

2021-05-25 17:55 UTC, mariusgiger commented on types/tekelek/TEK766/uplink.js
> +    data.limit1 = !!Number(bits.substr(23, 1));
why is limit 1 at 23?

2021-05-25 17:55 UTC, mariusgiger commented on types/tekelek/TEK766/uplink.js
> +      emit("sample", { data, topic: "current_alarm" });
why emit here?

2021-05-25 17:55 UTC, mariusgiger commented on types/tekelek/TEK766/uplink.js
> +      emit("sample", { data, topic: "current" });
why emit here?

2021-05-25 17:55 UTC, mariusgiger commented on types/tekelek/TEK766/uplink.js
> +    data.fmVersion = `${Bits.bitsToUnsigned(
extract to variables before concatenating the string

2021-05-25 17:55 UTC, mariusgiger commented on types/tekelek/TEK766/uplink.js
> +    data.aktive = Bits.bitsToUnsigned(bits.substr(50, 1));
aktive? active

2021-05-25 17:55 UTC, mariusgiger commented on types/tekelek/TEK766/uplink.js
> +    data.RSSI = -Bits.bitsToUnsigned(bits.substr(64, 8));
either always use small letters srssi or always capital letters RSSI

2021-05-25 17:55 UTC, mariusgiger commented on types/tekelek/TEK766/uplink.js
> +  emit("sample", { data, topic });
better move this up to the respective cases

2021-05-25 17:55 UTC, mariusgiger commented on types/tekelek/TEK766/uplink.js
> +    data.meassurements = min1 * 256 + min2;
typo meassurements -> measurements

2021-05-25 17:55 UTC, mariusgiger commented on types/tekelek/TEK766/uplink.js
> +    data.battery = Bits.bitsToUnsigned(bits.substr(80, 8));
batteryLevel?

2021-05-25 17:55 UTC, mariusgiger commented on types/tekelek/TEK766/uplink.spec.js
> +    });
add tests for the other payload types

2021-06-02 14:56 UTC, J2thatsme commented on types/tekelek/TEK766/uplink.js
> +    data.limit1 = !!Number(bits.substr(23, 1));
skipping unused bits

2021-06-08 14:33 UTC, mariusgiger approved these changes

2021-06-08 14:50 UTC, merged