added digital matter oyster
akenza-io/device-type-library pull request #67
Opened 2021-04-29 16:29 UTC by J2thatsme

2021-04-29 17:58 UTC, mariusgiger requested changes
some comments

2021-04-29 17:58 UTC, mariusgiger commented on types/digitalMatter/oyster/uplink.js
> +    if (decoded.latitudeDeg >= 0x80000000) // 2^31
use brackets

2021-04-29 17:58 UTC, mariusgiger commented on types/digitalMatter/oyster/uplink.js
> +function parseHexString(str) {
use bits?

2021-04-29 17:58 UTC, mariusgiger commented on types/digitalMatter/oyster/uplink.js
> +    if (decoded.longitudeDeg >= 0x80000000) // 2^31
brackets

2021-04-29 17:58 UTC, mariusgiger commented on types/digitalMatter/oyster/uplink.js
> +    if (decoded.longitudeDeg >= 0x800000) // 2^23
brackets

2021-04-29 17:58 UTC, mariusgiger commented on types/digitalMatter/oyster/lifecycle.schema.json
> +      "title": "Average GPS freshening time",
freshening?

2021-04-29 17:58 UTC, mariusgiger commented on types/digitalMatter/oyster/lifecycle.schema.json
> +      "description": "Transmition count"
typo transmission

2021-04-29 17:58 UTC, mariusgiger commented on types/digitalMatter/oyster/downlink_ack.schema.json
> +    "sequence": {
rename to sequenceNumber

2021-04-29 17:58 UTC, mariusgiger commented on types/digitalMatter/oyster/position.schema.json
> +      "description": "equals true if no movement for configured period got detected (Needs to be activated)"
always start with capitals

2021-05-18 15:21 UTC, J2thatsme commented
@mariusgiger please check again

2021-05-18 17:35 UTC, mariusgiger commented on types/digitalMatter/oyster/uplink.js
> +  var payload = event.data.payload_hex;
isn't it always payloadHex?

2021-05-18 17:36 UTC, mariusgiger commented on types/digitalMatter/oyster/uplink.spec.js
> +          port: 1,
please also add tests for the other ports

2021-05-18 17:36 UTC, mariusgiger submitted a review, later dismissed
looks clean, some comments

2021-05-18 17:37 UTC, mariusgiger commented
@J2thatsme please add a changelog entry

2021-05-19 12:35 UTC, J2thatsme commented on types/digitalMatter/oyster/uplink.js
> +  var payload = event.data.payload_hex;
No

2021-05-19 14:32 UTC, mariusgiger approved these changes

2021-05-20 08:51 UTC, merged