Cm 4
akenza-io/device-type-library pull request #78
Opened 2021-05-31 14:34 UTC by J2thatsme

2021-05-31 15:00 UTC, mariusgiger requested changes
looks good, some comments

2021-06-01 08:08 UTC, mariusgiger commented on types/comtac/CM-2/uplink.spec.js
> +        if (value.topic === "lifecyle") {
correct topic

2021-06-01 08:09 UTC, mariusgiger commented on types/comtac/CM-2/uplink.spec.js
> +        if (value.topic === "lifecyle") {
is this if still required?

2021-06-01 08:10 UTC, mariusgiger commented on types/comtac/CM-4/uplink.spec.js
> +        if (value.topic === "lifecyle") {
this if is not required, correct topic

2021-06-01 08:10 UTC, mariusgiger commented on types/comtac/CM-4/uplink.spec.js
> +        if (value.topic === "history") {
this if is not required

2021-06-01 14:12 UTC, mariusgiger commented on types/comtac/CM-4/uplink.spec.js
> +        if (value.topic === "history") {
@J2thatsme this is not yet done

2021-06-01 14:13 UTC, mariusgiger commented on types/comtac/CM-2/uplink.spec.js
> +      utils.expectEmits((type, value) => {
readd this to make the tests work

2021-06-01 14:30 UTC, J2thatsme commented on types/comtac/CM-2/uplink.spec.js
> +      utils.expectEmits((type, value) => {
ups sorry

2021-06-01 15:05 UTC, mariusgiger approved these changes

2021-06-01 15:27 UTC, merged