Enginko
akenza-io/device-type-library pull request #94
Opened 2021-08-12 15:57 UTC by J2thatsme

2021-08-12 18:54 UTC, mariusgiger requested changes
please add schemas for all topics

2021-08-12 18:54 UTC, mariusgiger commented on types/enginko/MCF-LW12CO2E/uplink.js
> +    if (isItNumber(value)) {
rename to isNumeric

2021-08-12 18:54 UTC, mariusgiger commented on types/enginko/MCF-LW12CO2E/uplink.js
> +      content = parseCo2(payload.trim(), false); // false is for new sensor
what does isNewSensor mean?

2021-08-13 08:57 UTC, J2thatsme commented on types/enginko/MCF-LW12CO2E/co2.schema.json
> +      "description": "RFU",
idk gonna delete it

2021-08-13 09:06 UTC, mariusgiger commented on types/enginko/MCF-LW12CO2E/co2.schema.json
> +      "description": "RFU",
rather find it our :D

2021-08-13 10:55 UTC, sevyakenza commented on types/enginko/MCF-LW12CO2E/meta.json
> +  "description": "This device reads temperature, humidity, pressure, light intensity, air quality (expressed as IAQ or bVOC value) and CO2 and sends collected data over the LoRaWAN® network. 3 traffi
@J2thatsme please use the description defined in the task:  This device reads temperature, humidity, pressure, light intensity, air quality (expressed as IAQ or bVOC value) and CO2. 3 traffic light LEDs for air quality display with adjustable brightness. Ideally suited for a wide range of applications such as building automation, condition monitoring, predictive maintenance, security, healthcare and many more use cases.

2021-08-13 10:55 UTC, sevyakenza commented on types/enginko/MCF-LW12CO2E/co2.schema.json
> +  "$id": "https://akenza.io/dragino/lse01/default.schema.json",
@J2thatsme this seems to be wrong

2021-08-13 11:01 UTC, J2thatsme commented on types/enginko/MCF-LW12CO2E/co2.schema.json
> +  "$id": "https://akenza.io/dragino/lse01/default.schema.json",
fixed

2021-08-13 11:34 UTC, J2thatsme commented on types/enginko/MCF-LW12CO2E/uplink.js
> +      content = parseCo2(payload.trim(), false); // false is for new sensor
looks like different encryption

2021-08-18 10:10 UTC, mariusgiger approved these changes

2021-08-18 10:11 UTC, mariusgiger commented on types/enginko/MCF-LW12CO2E/uplink.js
> +    // TODO why are the measurements converted to one object? this will lead to duplicated keys and eventually only contain the latest measurement
@J2thatsme please plan a fix for this

2021-08-18 10:12 UTC, merged